apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlmcsd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vlmcsd
  template:
    metadata:
      labels:
        app: vlmcsd
    spec:
      containers:
      - name: vlmcsd-container
        image: mikolatero/vlmcsd
        ports:
        - containerPort: 1688

---

apiVersion: v1
kind: Service
metadata:
  name: vlmcsd-service
  labels:
    app: vlmcsd
spec:
  ports:
  - protocol: TCP
    targetPort: 1688
    port: 1688
    nodePort: 32000
  selector:
    app: vlmcsd
  type: NodePort
