apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: default  # Change this to your namespace if different
spec:
  redirectScheme:
    scheme: https
    permanent: true
