apiVersion: apps/v1
kind: Deployment
metadata:
  name: pudim-website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pudim-website
  template:
    metadata:
      labels:
        app: pudim-website
    spec:
      containers:
        - name: pudim-website-container
          image: lerenner/pudim-main-website:main
          ports:
          - containerPort: 80
        - name: tor-container
          image: osminogin/tor-simple:latest
          volumeMounts:
            - name: config-volume
              mountPath: /etc/tor
            - name: data-volume
              mountPath: /var/lib/tor
      volumes:
        - name: config-volume
          hostPath:
            path: /home/renner/mount/archive/archive/special/k8s/tor/conf
        - name: data-volume
          hostPath:
            path: /home/renner/mount/archive/archive/special/k8s/tor/data

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    :80 {
        root * /var/www/html
        encode gzip
        file_server browse
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: usp-archive-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usp-archive
  template:
    metadata:
      labels:
        app: usp-archive
    spec:
      containers:
        - name: usp-archive-container
          image: caddy:latest
          ports:
          - containerPort: 80
          volumeMounts:
            - name: data-volume
              mountPath: /var/www/html
            - name: config-volume
              mountPath: /etc/caddy
      volumes:
        - name: data-volume
          hostPath:
            path: /home/renner/mount/archive/archive/special/k8s/usp/
        - name: config-volume
          configMap:
            name: caddy-config
          
---

apiVersion: v1
kind: Service
metadata:
  name: pudim-service
  labels:
    app: pudim-website
spec:
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
  selector:
    app: pudim-website
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pudim-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
  - host: "pudim.xyz"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: pudim-service
            port:
              number: 80
      - pathType: Prefix
        path: "/usp"
        backend:
          service:
            name: usp-archive
            port:
              number: 80
  tls:
  - hosts:
    - pudim.xyz
    secretName: pudim-tls-secret
