apiVersion: apps/v1
kind: Deployment
metadata:
  name: pudim-main-website
  labels:
    app: pudim-main-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pudim-main-website
  template:
    metadata:
      labels:
        app: pudim-main-website
    spec:
      containers:
      - name: pudim-main-website
        image: lerenner/pudim-main-website:main
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: pudim-main-website
  name: pudim-main-website
spec:
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
  selector:
    app: pudim-main-website
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-pudim
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
  - host: "pudim.xyz"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: pudim-main-website
            port:
              number: 80
  tls:
  - hosts:
    - pudim.xyz
    secretName: pudim-tls-secret