apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-configmap
data:
  Caddyfile: |
    :80 {
      root * /var/www/html
      encode gzip
      file_server browse
      log {
          output file /tmp/access.log
      }
    }

---

# torrc Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: tor-configmap
data:
  torrc: |
    Log debug
    LogTimeGranularity 1
    DataDirectory /tmp
    HiddenServiceDir /var/tor
    HiddenServicePort 80 localhost:80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pudim-website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pudim-website
  template:
    metadata:
      labels:
        app: pudim-website
    spec:
      containers:
        - name: pudim-website-container
          image: lerenner/pudim-main-website:main
          ports:
          - containerPort: 80
          volumeMounts:
            - name: caddy-config-vol
              mountPath: /etc/caddy
        # - name: tor-container
        #   image: osminogin/tor-simple:latest
        #   volumeMounts:
        #     - name: tor-config-vol
        #       mountPath: /etc/tor
        #     - name: secret-key-vol
        #       mountPath: /var/tor
      volumes:
        # - name: tor-config-vol
        #   configMap:
        #     name: tor-configmap
        - name: caddy-config-vol
          configMap:
            name: caddy-configmap
        # - name: secret-key-vol
        #   secret:
        #     secretName: tor-pudim-secret-key
          
---

apiVersion: v1
kind: Service
metadata:
  name: pudim-service
  labels:
    app: pudim-website
spec:
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
  selector:
    app: pudim-website
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pudim-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
  - host: "pudim.xyz"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pudim-service
            port:
              number: 80
      - path: /usp
        pathType: Prefix
        backend:
          service:
            name: usp-archive-service
            port:
              number: 80
  tls:
  - hosts:
    - pudim.xyz
    secretName: pudim-tls-secret
