apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-openvpn-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission-openvpn
  template:
    metadata:
      labels:
        app: transmission-openvpn
    spec:
      containers:
      - name: transmission-openvpn-container
        image: haugene/transmission-openvpn
        imagePullPolicy: Always
        volumeMounts:
          - name: media
            mountPath: /videos
          - name: storage
            mountPath: /downloads
          - name: config
            mountPath: /config
          - name: openvpn
            mountPath: /etc/openvpn/custom
          - name: openvpn-credentials
            mountPath: /config/openvpn-credentials.txt
        env:
          - name: OPENVPN_PROVIDER
            value: "CUSTOM"
          - name: OPENVPN_CONFIG
            value: "mullvad_bg_sof"
          - name: OPENVPN_USERNAME
            valueFrom:
              secretKeyRef:
                name: mullvad-vpn-secret
                key: username
          - name: OPENVPN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mullvad-vpn-secret
                key: password
          - name: LOCAL_NETWORK
            value: "192.168.1.0/24"
          - name: TRANSMISSION_RPC_USERNAME
            valueFrom:
              secretKeyRef:
                name: mullvad-vpn-secret
                key: rpc_username
          - name: TRANSMISSION_RPC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mullvad-vpn-secret
                key: rpc_password
          - name: TRANSMISSION_RPC_AUTHENTICATION_REQUIRED
            value: "true"
        ports:
          - containerPort: 9091
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      volumes:
        - name: media
          hostPath:
            path: /home/renner/mount/archive/archive/Video/VIDEOS
        - name: storage
          hostPath:
            path: /home/renner/mount/archive/archive/special/k8s/transmission-openvpn/storage
        - name: config
          hostPath:
            path: /home/renner/mount/archive/archive/special/k8s/transmission-openvpn/configFiles/
        - name: openvpn
          hostPath:
            path: /home/renner/mount/archive/archive/special/k8s/transmission-openvpn/custom/
        - name: openvpn-credentials
          hostPath:
            path: /home/renner/mount/archive/archive/special/k8s/transmission-openvpn/custom/openvpn-credentials.txt

---

apiVersion: v1
kind: Service
metadata:
  name: transmission-openvpn-service
  labels:
    app: transmission-openvpn
spec:
  ports:
  - protocol: TCP
    targetPort: 9091
    port: 9091
    nodePort: 32084
  selector:
    app: transmission-openvpn
  type: NodePort
