apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: wireguard-container
        image: lscr.io/linuxserver/wireguard:latest
        ports:
        - containerPort: 51820
          protocol: UDP
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Etc/UTC"
          # Optional environment variables
          - name: SERVERURL
            value: "home.pudim.xyz"
          - name: SERVERPORT
            value: "32046"
          - name: PEERS
            value: "10"
          - name: PEERDNS
            value: "auto"
          # - name: INTERNAL_SUBNET
          #   value: "10.13.13.0"
          - name: ALLOWEDIPS
            value: "0.0.0.0/0"
          # - name: PERSISTENTKEEPALIVE_PEERS
          #   value: ""
          # - name: LOG_CONFS
          #   value: "true"
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        hostPath:
          path: /home/renner/mount/archive/archive/special/k8s/wireguard

---

apiVersion: v1
kind: Service
metadata:
  name: wireguard-service
  labels:
    app: wireguard
spec:
  ports:
  - protocol: UDP
    targetPort: 51820
    port: 51820
    nodePort: 32046
  selector:
    app: wireguard
  type: NodePort