apiVersion: v1
kind: ConfigMap
metadata:
  name: files-configmap
data:
  Caddyfile: |
    :80 {
      root * /var/www/html
      encode gzip
      file_server browse
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pudim-files-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pudim-files
  template:
    metadata:
      labels:
        app: pudim-files
    spec:
      containers:
        - name: pudim-files-container
          image: caddy:latest
          ports:
          - containerPort: 80
          volumeMounts:
            - name: files-config-vol
              mountPath: /etc/caddy
            - name: host-files-folder
              mountPath: /var/www/html
          imagePullPolicy: Always
      volumes:
        - name: files-config-vol
          configMap:
            name: files-configmap
        - name: host-files-folder
          hostPath:
            path: /home/renner/mount/archive/archive/special/k8s/files
          
---

apiVersion: v1
kind: Service
metadata:
  name: pudim-files-service
  labels:
    app: pudim-files
spec:
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
  selector:
    app: pudim-files
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pudim-files-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
  - host: "files.pudim.xyz"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pudim-files-service
            port:
              number: 80
  tls:
  - hosts:
    - files.pudim.xyz
    secretName: pudim-files-tls-secret

