apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddclient-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddclient
  template:
    metadata:
      labels:
        app: ddclient
    spec:
      containers:
        - name: ddclient-container
          image: lscr.io/linuxserver/ddclient:latest
          volumeMounts:
            - name: config-volume
              mountPath: /etc/ddclient
            - name: secret-volume
              mountPath: /secret
      volumes:
        - name: config-volume
          configMap:
            name: ddclient-config
        - name: secret-volume
          secret:
            secretName: ddclient-secret


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ddclient-config
data:
  ddclient.conf: |
    ssl=yes
    use=web,web=checkip-dyndns-org/
    protocol=cloudflare
    use=web,web=https://api.ipify.org/
    login=$(cat /secret/login)
    password=$(cat /secret/password)
    zone=pudim.xyz
    home.pudim.xyz
