apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto-container
        image: eclipse-mosquitto:latest
        ports:
        - containerPort: 1883
        env:
        - name: ALLOW_UNSECURE_MODE
          value: "true"
        volumeMounts:
        - name: config-volume
          mountPath: /mosquitto/config
      volumes:
      - name: config-volume
        configMap:
          name: mosquitto-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    allow_anonymous true
    listener 1883
    persistence true
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log
      
---

apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  labels:
    app: mosquitto
spec:
  ports:
  - protocol: TCP
    targetPort: 1883
    port: 1883
    nodePort: 32032
  selector:
    app: mosquitto
  type: NodePort
