apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-data-logger-configmap
data:
  main.txt: |
    mosquitto-service.pudimnetes.svc.cluster.local
    1883
    dht22/humidity,dht22/temperature,fridge/temperature

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana-container
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-config-volume
              mountPath: /var/lib/grafana
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_NAME
              value: "Main Org."
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Viewer"
            - name: GF_AUTH_ANONYMOUS_HIDE_VERSION
              value: "true"
        - name: influxdb-container
          image: influxdb:latest
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: influx-database-volume
              mountPath: /var/lib/influxdb2
        - name: mqtt-data-logger-container
          image: lerenner/mqtt-data-logger:main
          imagePullPolicy: Always
          volumeMounts:
            - name: influx-database-volume
              mountPath: /var/lib/influxdb2
            - name: mqtt-data-logger-configmap-volume
              mountPath: /config
            - name: grafana-secrets-volume
              mountPath: /secrets
      volumes:
        - name: grafana-config-volume
          hostPath:
            path: /home/renner/special/k8s/grafana/grafanaConfig
        - name: influx-database-volume
          hostPath:
            path: /home/renner/special/k8s/grafana/influxDB
        - name: mqtt-data-logger-configmap-volume
          configMap:
            name: mqtt-data-logger-configmap
            items:
              - key: main.txt
                path: main.txt
        - name: grafana-secrets-volume
          secret:
            secretName: grafana-secrets
            items:
              - key: token
                path: token
              - key: org
                path: org
              - key: bucket
                path: bucket

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: grafana.pudim.xyz
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: grafana-service
                port:
                  number: 3000
  tls:
    - hosts:
        - grafana.pudim.xyz
      secretName: grafana-tls