apiVersion: v1
kind: ConfigMap
metadata:
  name: pudim-mailer-configmap
data:
  hostname: |
    mosquitto-service.pudimnetes.svc.cluster.local
  port: |
    1883

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pudim-mailer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pudim-mailer
  template:
    metadata:
      labels:
        app: pudim-mailer
    spec:
      containers:
        - name: pudim-mailer-container
          image: lerenner/pudim-mailer:main
          imagePullPolicy: Always
          volumeMounts:
            - name: pudim-mailer-configmap-volume
              mountPath: /config
      volumes:
        - name: pudim-mailer-configmap-volume
          configMap:
            name: telegram-messenger-configmap
            items:
              - key: hostname
                path: hostname
              - key: port
                path: port

---

apiVersion: v1
kind: Service
metadata:
  name: pudim-mailer-service
spec:
  selector:
    app: pudim-mailer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pudim-mailer-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: mail.pudim.xyz
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: pudim-mailer-service
                port:
                  number: 3000
  tls:
    - hosts:
        - mail.pudim.xyz
      secretName: pudim-mail-tls