apiVersion: apps/v1
kind: Deployment
metadata:
  name: ios-logger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ios-logger
  template:
    metadata:
      labels:
        app: ios-logger
    spec:
      containers:
        - name: ios-logger-container
          image: lerenner/ios-logger:main
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          volumeMounts:
            - name: data-volume
              mountPath: /data
      volumes:
        - name: data-volume
          hostPath:
            path: /home/renner/mount/archive/archive/special/k8s/ios/

---

apiVersion: v1
kind: Service
metadata:
  name: ios-logger-service
  labels:
    app: ios-logger
spec:
  ports:
  - protocol: TCP
    targetPort: 3000
    port: 3000
  selector:
    app: ios-logger
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ios-logger-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: "ios.pudim.xyz"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ios-logger-service
            port:
              number: 3000
  tls:
  - hosts:
    - ios.pudim.xyz
    secretName: ios-logger-tls-secret